name: liss
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asciitree=0.3.3
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.18
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - black=24.4.2
  - bleach=6.1.0
  - blosc=1.21.5
  - bmipy=2.0.1
  - bokeh=3.4.1
  - bottleneck=1.3.8
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cartopy=0.23.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfgrib=0.9.11.0
  - cfitsio=4.4.0
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contextily=1.6.0
  - contourpy=1.2.1
  - cramjam=2.8.3
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2023.8.1
  - dask-core=2023.8.1
  - dask-geopandas=0.3.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.8.1
  - eccodes=2.35.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fasteners=0.17.3
  - fastparquet=2024.2.0
  - findlibs=0.0.5
  - fiona=1.9.6
  - fmt=10.2.1
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2024.3.1
  - gdal=3.8.5
  - gdptools=0.2.9
  - geographiclib=2.0
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geopy=2.4.1
  - geos=3.12.1
  - geotiff=1.7.1
  - git=2.45.0
  - h11=0.14.0
  - h2=4.1.0
  - h5netcdf=1.3.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - intel-openmp=2024.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isoduration=20.11.0
  - jasper=4.2.4
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=2.4
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.1
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libdeflate=1.20
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.8.5
  - libglib=2.80.0
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libparquet=15.0.2
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - metpy=1.6.2
  - minizip=4.0.5
  - mistune=3.0.2
  - mkl=2024.1.0
  - msgpack-python=1.0.7
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - netcdf4=1.6.5
  - networkx=3.3
  - notebook-shim=0.2.4
  - numba=0.59.1
  - numba_celltree=0.1.6
  - numcodecs=0.12.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=2.0.0
  - overrides=7.7.0
  - packaging=24.0
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pathspec=0.12.1
  - patsy=0.5.6
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pint=0.23
  - pip=24.0
  - pixman=0.43.4
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.1
  - pooch=1.8.1
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - proj=9.4.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=15.0.2
  - pycparser=2.22
  - pydantic=1.10.14
  - pydap=3.4.0
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.9.0
  - python-eccodes=1.7.0
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - rasterio=1.3.10
  - re2=2023.09.01
  - referencing=0.35.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rioxarray=0.15.5
  - rpds-py=0.18.1
  - rtree=1.2.0
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - send2trash=1.8.3
  - setuptools=69.5.1
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spdlog=1.13.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - tbb=2021.12.0
  - tblib=3.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tiledb=2.22.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - webob=1.8.7
  - websocket-client=1.8.0
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=2024.3.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xugrid=0.10.0
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - zarr=2.18.0
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - bmi-python==0.3.0
      - docopt==0.6.1
      - docopts==0.6.1
      - flopy==3.7.0.dev0
      - modflowapi==0.3.0.dev0
      - xmipy==1.5.0
